"use client";
import Link from "next/link";
import { usePerson } from "../services/people.queries";
type Detail = { id: string; name: string; title: string | null; email: string | null; phone: string | null; location: string | null; linkedinUrl: string | null; organization?: { name: string } | null; leads: { id: string; name: string; status: string }[]; research: { id: string; status: string; summary: string | null }[]; activities: { id: string; title: string; createdAt: string }[] };
export default function PersonDetailsPage({ id }: { id: string }) {
  const query = usePerson(id);
  const person = query.data as unknown as Detail | undefined;
  if (query.isPending) return <p className="text-sm text-muted-foreground">Loading person…</p>;
  if (query.isError || !person) return <p role="alert" className="text-sm text-destructive">{query.error?.message || "Person not found."}</p>;
  return <section><Link href="/people" className="text-sm text-primary hover:underline">← People</Link><p className="mt-5 text-sm text-muted-foreground">{person.title || "Potential contact"}{person.organization ? ` · ${person.organization.name}` : ""}</p><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="mt-1 text-3xl font-semibold">{person.name}</h1><Link href={`/people/${id}/edit`} target="_blank" className="rounded-lg border px-3 py-2 text-sm">Edit person</Link></div><div className="mt-4 space-y-1 text-sm text-muted-foreground">{person.email && <p>{person.email}</p>}{person.phone && <p>{person.phone}</p>}{person.location && <p>{person.location}</p>}{person.linkedinUrl && <a className="text-primary hover:underline" href={person.linkedinUrl} target="_blank" rel="noreferrer">LinkedIn ↗</a>}</div>
    <div className="mt-6 grid gap-4 md:grid-cols-2"><div className="rounded-xl border p-5"><h2 className="font-semibold">Leads</h2>{person.leads.length ? person.leads.map(l => <p key={l.id} className="mt-3 text-sm"><Link href={`/leads/${l.id}`} className="hover:underline">{l.name}</Link> · {l.status}</p>) : <p className="mt-3 text-sm text-muted-foreground">No leads linked.</p>}</div><div className="rounded-xl border p-5"><h2 className="font-semibold">Research</h2>{person.research.length ? person.research.map(r => <p key={r.id} className="mt-3 text-sm">{r.status} · {r.summary || "No summary recorded"}</p>) : <p className="mt-3 text-sm text-muted-foreground">No research runs.</p>}</div><div className="rounded-xl border p-5 md:col-span-2"><h2 className="font-semibold">Recent activities</h2>{person.activities.length ? person.activities.map(a => <p key={a.id} className="mt-3 text-sm">{a.title} · {new Date(a.createdAt).toLocaleDateString()}</p>) : <p className="mt-3 text-sm text-muted-foreground">No recent activities.</p>}</div></div>
  </section>;
}
