"use client";
import Link from "next/link";
import { useLead } from "../services/leads.queries";
type Detail = { id: string; name: string; status: string; source: string; notes: string | null; organization?: { name: string; industry: string | null; location: string | null; city: string | null } | null; person?: { name: string; title: string | null; email: string | null } | null; research: { id: string; status: string; summary: string | null }[]; activities: { id: string; title: string; createdAt: string }[] };
export default function LeadDetailsPage({ id }: { id: string }) {
  const query = useLead(id);
  const lead = query.data as unknown as Detail | undefined;
  if (query.isPending) return <p className="text-sm text-muted-foreground">Loading lead…</p>;
  if (query.isError || !lead) return <p role="alert" className="text-sm text-destructive">{query.error?.message || "Lead not found."}</p>;
  return <section><Link href="/leads" className="text-sm text-primary hover:underline">← Leads</Link><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-muted-foreground">{lead.status} · {lead.source}</p><Link href={`/leads/${id}/edit`} target="_blank" className="rounded-lg border px-3 py-2 text-sm">Edit lead</Link></div><h1 className="mt-1 text-3xl font-semibold">{lead.name}</h1>{lead.notes && <p className="mt-4 max-w-3xl whitespace-pre-wrap text-sm leading-6">{lead.notes}</p>}
    <div className="mt-6 grid gap-4 md:grid-cols-2"><div className="rounded-xl border p-5"><h2 className="font-semibold">Organization</h2><p className="mt-3">{lead.organization?.name || "No organization linked."}</p>{lead.organization && <p className="mt-1 text-sm text-muted-foreground">{lead.organization.industry || "Industry not provided"} · {lead.organization.location || lead.organization.city || "Location not provided"}</p>}</div><div className="rounded-xl border p-5"><h2 className="font-semibold">Person</h2><p className="mt-3">{lead.person?.name || "No person linked."}</p>{lead.person && <p className="mt-1 text-sm text-muted-foreground">{lead.person.title || "Title not provided"} · {lead.person.email || "No email"}</p>}</div></div>
    <div className="mt-6 grid gap-4 md:grid-cols-2"><div className="rounded-xl border p-5"><h2 className="font-semibold">Research</h2>{lead.research.length ? lead.research.map(r => <p key={r.id} className="mt-3 text-sm">{r.status} · {r.summary || "No summary recorded"}</p>) : <p className="mt-3 text-sm text-muted-foreground">No research has been run for this lead.</p>}</div><div className="rounded-xl border p-5"><h2 className="font-semibold">Recent activity</h2>{lead.activities.length ? lead.activities.map(a => <p key={a.id} className="mt-3 text-sm">{a.title} · {new Date(a.createdAt).toLocaleString()}</p>) : <p className="mt-3 text-sm text-muted-foreground">No activity recorded.</p>}</div></div>
  </section>;
}
