"use client";
import Link from "next/link";
import { useOrganization } from "../services/organizations.queries";
type Detail = { id: string; name: string; website: string | null; industry: string | null; description: string | null; location: string | null; city: string | null; country: string | null; linkedinUrl: string | null; people: { id: string; name: string; title: string | null }[]; leads: { id: string; name: string; status: string }[]; research: { id: string; status: string; summary: string | null }[]; activities: { id: string; title: string; createdAt: string }[] };
export default function OrganizationDetailsPage({ id }: { id: string }) {
  const query = useOrganization(id);
  const organization = query.data as unknown as Detail | undefined;
  if (query.isPending) return <p className="text-sm text-muted-foreground">Loading organization…</p>;
  if (query.isError || !organization) return <p role="alert" className="text-sm text-destructive">{query.error?.message || "Organization not found."}</p>;
  return <section><Link href="/organizations" className="text-sm text-primary hover:underline">← Organizations</Link><p className="mt-5 text-sm text-muted-foreground">{organization.industry || "Organization"} · {[organization.city, organization.country].filter(Boolean).join(", ") || organization.location || "Location not provided"}</p><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="mt-1 text-3xl font-semibold">{organization.name}</h1><Link href={`/organizations/${id}/edit`} target="_blank" className="rounded-lg border px-3 py-2 text-sm">Edit organization</Link></div>{organization.description && <p className="mt-4 max-w-3xl text-sm leading-6">{organization.description}</p>}
    <div className="mt-5 flex flex-wrap gap-4 text-sm">{organization.website && <a className="text-primary hover:underline" href={organization.website} target="_blank" rel="noreferrer">Website ↗</a>}{organization.linkedinUrl && <a className="text-primary hover:underline" href={organization.linkedinUrl} target="_blank" rel="noreferrer">LinkedIn ↗</a>}</div>
    <div className="mt-6 grid gap-4 lg:grid-cols-2"><div className="rounded-xl border p-5"><h2 className="font-semibold">People</h2>{organization.people.length ? organization.people.map(p => <p key={p.id} className="mt-3 text-sm">{p.name} <span className="text-muted-foreground">{p.title || ""}</span></p>) : <p className="mt-3 text-sm text-muted-foreground">No people linked.</p>}</div><div className="rounded-xl border p-5"><h2 className="font-semibold">Leads</h2>{organization.leads.length ? organization.leads.map(l => <p key={l.id} className="mt-3 text-sm"><Link className="hover:underline" href={`/leads/${l.id}`}>{l.name}</Link> <span className="text-muted-foreground">· {l.status}</span></p>) : <p className="mt-3 text-sm text-muted-foreground">No leads linked.</p>}</div><div className="rounded-xl border p-5"><h2 className="font-semibold">Research</h2>{organization.research.length ? organization.research.map(r => <p key={r.id} className="mt-3 text-sm">{r.status} · {r.summary || "No summary recorded"}</p>) : <p className="mt-3 text-sm text-muted-foreground">No research runs.</p>}</div><div className="rounded-xl border p-5"><h2 className="font-semibold">Recent activities</h2>{organization.activities.length ? organization.activities.map(a => <p key={a.id} className="mt-3 text-sm">{a.title} · {new Date(a.createdAt).toLocaleDateString()}</p>) : <p className="mt-3 text-sm text-muted-foreground">No recent activities.</p>}</div></div>
  </section>;
}
